# Dockerfile for Nitro Enclave server
FROM ubuntu:24.04 AS runtime

# Install build dependencies
RUN apt-get update && apt-get install -y gcc g++ libssl-dev make cmake git libcbor-dev && rm -rf /var/lib/apt/lists/*

# # Build libcbor from source (not in default yum repos)
# RUN git clone --depth 1 --branch v0.10.2 https://github.com/PJK/libcbor.git /tmp/libcbor && \
#     cd /tmp/libcbor && \
#     cmake -DCMAKE_BUILD_TYPE=Release -DCBOR_PRETTY_PRINTER=OFF . && \
#     make && \
#     make install && \
#     ldconfig && \
#     rm -rf /tmp/libcbor

# Copy source
COPY enclave_server.c /app/enclave_server.c

# Compile
WORKDIR /app
RUN gcc -o enclave_server enclave_server.c -lcrypto -lcbor -Wall -O2

# The enclave server will be PID 1
CMD ["/app/enclave_server"]
